with open(r'd:\Riddhi\Meter_Scanner\app.py', 'r', encoding='utf-8') as f:
    content = f.read()

start_marker = "@app.route('/chat', methods=['POST'])"
end_marker   = "@app.route('/login'"
start_idx = content.find(start_marker)
end_idx   = content.find(end_marker, start_idx)
assert start_idx != -1 and end_idx != -1, "Markers not found"

NEW_CHAT = (
    "@app.route('/chat', methods=['POST'])\n"
    "def chat():\n"
    "    try:\n"
    "        data = request.get_json()\n"
    "        msg  = data.get('message', '').lower().strip()\n"
    "        nums = re.findall(r'\\d+\\.?\\d*', msg)\n"
    "\n"
    "        OFF_TOPIC = ['weather','cricket','football','movie','song','recipe',\n"
    "            'politics','news','stock','crypto','bitcoin','relationship',\n"
    "            'love','joke','poem','write code','javascript','translate',\n"
    "            'capital of','population of','president','prime minister',\n"
    "            'who invented','physics','mathematics','game','sport',\n"
    "            'fashion','travel','hotel','flight','instagram','facebook',\n"
    "            'twitter','youtube','tiktok']\n"
    "\n"
    "        if any(k in msg for k in OFF_TOPIC):\n"
    "            r = ('Sorry, I can only help with Meter Scanner Pro topics! \\u26a1\\n\\n'\n"
    "                 'I specialise in:\\n'\n"
    "                 '\\U0001f4f7 Meter scanning and OCR\\n'\n"
    "                 '\\U0001f4b0 Bill calculation\\n'\n"
    "                 '\\U0001f4ca Analytics and trends\\n'\n"
    "                 '\\U0001f514 Alerts and budgets\\n'\n"
    "                 '\\U0001f4a1 Energy-saving tips\\n'\n"
    "                 '\\U0001f527 Troubleshooting\\n\\n'\n"
    "                 'Please ask about your meters and I\\'ll be happy to help! \\U0001f60a')\n"
    "\n"
    "        elif any(w in msg for w in ['hello','hi','hey','greetings','good morning','good afternoon','good evening','namaste']):\n"
    "            r = ('Hello! \\U0001f44b I\\'m **MeterBot**, your smart energy assistant.\\n\\n'\n"
    "                 'I can help you with:\\n'\n"
    "                 '\\U0001f4f7 Scan meters | \\U0001f4b0 Calculate bills | \\U0001f4ca Analytics\\n'\n"
    "                 '\\U0001f514 Alerts | \\U0001f4a1 Energy tips | \\U0001f527 Troubleshooting\\n\\n'\n"
    "                 'What would you like help with today?')\n"
    "\n"
    "        elif any(w in msg for w in ['who are you','what are you','your name','introduce','about you','what can you do']):\n"
    "            r = ('I\\'m **MeterBot** \\U0001f916 \\u2014 the AI assistant for Meter Scanner Pro.\\n\\n'\n"
    "                 'I can help with:\\n'\n"
    "                 '\\u2022 \\U0001f4f7 AI meter scanning and OCR\\n'\n"
    "                 '\\u2022 \\U0001f4b0 Bill calculation with Indian slab rates\\n'\n"
    "                 '\\u2022 \\U0001f4ca Usage analytics and monthly trends\\n'\n"
    "                 '\\u2022 \\U0001f514 Smart alerts and threshold notifications\\n'\n"
    "                 '\\u2022 \\U0001f4c5 Monthly budget planning\\n'\n"
    "                 '\\u2022 \\U0001f331 Energy saving tips\\n'\n"
    "                 '\\u2022 \\U0001f527 Scanning troubleshooting\\n'\n"
    "                 '\\u2022 \\U0001f4c1 CSV data export\\n'\n"
    "                 '\\u2022 \\U0001f464 Account and Google login help\\n\\n'\n"
    "                 'Available 24/7 \\u26a1')\n"
    "\n"
    "        elif any(w in msg for w in ['scan','capture','camera','ocr','take photo','read meter','how to scan','meter reading']):\n"
    "            r = ('How to scan your meter: \\U0001f4f7\\n\\n'\n"
    "                 '1\\ufe0f\\u20e3 Dashboard \\u2192 Scan Meter\\n'\n"
    "                 '2\\ufe0f\\u20e3 Allow camera access\\n'\n"
    "                 '3\\ufe0f\\u20e3 Centre the meter in the frame\\n'\n"
    "                 '4\\ufe0f\\u20e3 Ensure good, even lighting\\n'\n"
    "                 '5\\ufe0f\\u20e3 Tap Capture \\u2014 OCR reads instantly!\\n\\n'\n"
    "                 '\\u2705 Supports Digital, Analog, Smart, Water and Gas meters\\n\\n'\n"
    "                 '\\U0001f4a1 Tip: Clean the display before scanning for best accuracy.')\n"
    "\n"
    "        elif any(w in msg for w in ['slab','tariff','per unit','electricity rate','kwh rate','unit rate']):\n"
    "            r = ('\\u26a1 Indian Electricity Rate Slabs\\n\\n'\n"
    "                 '0\\u201350 units    \\u2192 \\u20b92.50/unit (Lifeline)\\n'\n"
    "                 '51\\u2013100 units  \\u2192 \\u20b93.50/unit\\n'\n"
    "                 '101\\u2013300 units \\u2192 \\u20b94.50/unit\\n'\n"
    "                 '301\\u2013500 units \\u2192 \\u20b96.50/unit\\n'\n"
    "                 '500+ units    \\u2192 \\u20b98.50/unit\\n\\n'\n"
    "                 'Extra: Fuel surcharge 15% | GST 18% | Meter rent \\u20b925\\n'\n"
    "                 '\\u2600\\ufe0f Summer +20% | \\u2744\\ufe0f Winter -10% | Peak hrs +25%')\n"
    "\n"
    "        elif any(w in msg for w in ['bill','calculate','cost','charge','amount','invoice','payment']):\n"
    "            if len(nums) >= 2:\n"
    "                u, rate = float(nums[0]), float(nums[1])\n"
    "                energy = u * rate; gst = energy * 0.18; total = energy + gst + 25\n"
    "                r = (f'\\U0001f4b0 Bill Result\\n\\n'\n"
    "                     f'Units: {u} kWh | Rate: \\u20b9{rate}/unit\\n'\n"
    "                     f'Energy charge : \\u20b9{energy:.2f}\\n'\n"
    "                     f'Meter rent    : \\u20b925.00\\n'\n"
    "                     f'GST (18%%.)   : \\u20b9{gst:.2f}\\n'\n"
    "                     f'Total Bill    : \\u20b9{total:.2f}\\n\\n'\n"
    "                     'See Bills page for full slab breakdown!')\n"
    "            elif len(nums) == 1:\n"
    "                u = float(nums[0])\n"
    "                r = (f'Got it \\u2014 {u} units! \\U0001f4ca\\n\\n'\n"
    "                     f'Share the rate per unit (\\u20b9) for the total.\\n'\n"
    "                     f\"Example: '{u} units at \\u20b96 per unit'\\n\\n\"\n"
    "                     'Or visit Bills page for automatic calculation!')\n"
    "            else:\n"
    "                r = ('I can calculate your electricity bill! \\U0001f4b0\\n\\n'\n"
    "                     'Indian electricity slabs:\\n'\n"
    "                     '\\u2022 0\\u201350 units \\u2192 \\u20b92.50/unit\\n'\n"
    "                     '\\u2022 51\\u2013100   \\u2192 \\u20b93.50/unit\\n'\n"
    "                     '\\u2022 101\\u2013300  \\u2192 \\u20b94.50/unit\\n'\n"
    "                     '\\u2022 301\\u2013500  \\u2192 \\u20b96.50/unit\\n'\n"
    "                     '\\u2022 500+        \\u2192 \\u20b98.50/unit\\n\\n'\n"
    "                     'Tell me your units consumed and I\\'ll calculate it!')\n"
    "\n"
    "        elif any(w in msg for w in ['history','past reading','analytics','trend','graph','monthly','consumption','track','usage']):\n"
    "            r = ('\\U0001f4ca Reading History and Analytics\\n\\n'\n"
    "                 '\\U0001f539 Readings Page \\u2192 All past scans with timestamps\\n'\n"
    "                 '\\U0001f539 Dashboard \\u2192 6-month usage trend chart\\n'\n"
    "                 '\\U0001f539 Analytics \\u2192 Monthly comparisons and peak days\\n\\n'\n"
    "                 'Stats: monthly average, month-on-month change, efficiency score (A+ to C), peak/low days\\n\\n'\n"
    "                 '\\U0001f4c1 Export all readings to CSV from the Readings page!')\n"
    "\n"
    "        elif any(w in msg for w in ['alert','notification','warning','threshold','notify']):\n"
    "            r = ('\\U0001f514 Smart Alerts\\n\\n'\n"
    "                 'Dashboard \\u2192 Alerts to configure:\\n\\n'\n"
    "                 '\\u2022 \\u26a1 High usage alert\\n'\n"
    "                 '\\u2022 \\U0001f4b0 Bill threshold alert\\n'\n"
    "                 '\\u2022 \\U0001f4c5 Missed reading reminder\\n'\n"
    "                 '\\u2022 \\U0001f527 Maintenance due reminder\\n\\n'\n"
    "                 'Click Add Alert, set type and value, save \\u2014 done!')\n"
    "\n"
    "        elif any(w in msg for w in ['budget','limit','spending','budget planner']):\n"
    "            r = ('\\U0001f4c5 Budget Planner\\n\\n'\n"
    "                 'Alerts \\u2192 Budget Planner to:\\n\\n'\n"
    "                 '\\u2022 Set a monthly spending limit\\n'\n"
    "                 '\\u2022 Track estimated current spend\\n'\n"
    "                 '\\u2022 Get alerts near your limit\\n'\n"
    "                 '\\u2022 Compare budget vs actual\\n\\n'\n"
    "                 '\\U0001f4a1 Tip: Set 10-15% below last month\\'s bill to build savings!')\n"
    "\n"
    "        elif any(w in msg for w in ['tip','save energy','reduce','saving','efficient','lower bill']):\n"
    "            r = ('\\U0001f4a1 Energy Saving Tips\\n\\n'\n"
    "                 '\\U0001f3e0 Lighting: LED bulbs \\u2192 save up to 75%\\n'\n"
    "                 '\\u274a\\ufe0f Cooling: Set AC to 24\\u00b0C, use fans alongside\\n'\n"
    "                 '\\U0001f50c Standby: Unplug idle devices (saves ~10% of bill)\\n'\n"
    "                 '\\u23f0 Timing: Run heavy loads during off-peak (10PM\\u20136AM)\\n'\n"
    "                 '\\U0001f321\\ufe0f Insulate: Seal doors and windows\\n\\n'\n"
    "                 'Visit Energy Tips page in the app for personalised advice!')\n"
    "\n"
    "        elif any(w in msg for w in ['export','download','csv','report','data']):\n"
    "            r = ('\\U0001f4c1 Exporting Your Data\\n\\n'\n"
    "                 'Readings \\u2192 Export to CSV\\n\\n'\n"
    "                 'CSV includes: Reading value (kWh), Timestamp, OCR confidence, Status, Notes\\n\\n'\n"
    "                 'Open in Excel or Google Sheets for custom charts! \\U0001f4ca')\n"
    "\n"
    "        elif any(w in msg for w in ['maintenance','service','repair','schedule']):\n"
    "            r = ('\\U0001f527 Maintenance Scheduling\\n\\n'\n"
    "                 'Settings \\u2192 Maintenance to:\\n\\n'\n"
    "                 '\\u2022 Schedule meter inspections\\n'\n"
    "                 '\\u2022 Log completed maintenance\\n'\n"
    "                 '\\u2022 Get reminders before due dates\\n'\n"
    "                 '\\u2022 Track history per meter\\n\\n'\n"
    "                 'Regular maintenance ensures accurate readings! \\u2705')\n"
    "\n"
    "        elif any(w in msg for w in ['complaint','support','contact','dispute','wrong reading']):\n"
    "            r = ('\\U0001f4de Support and Complaints\\n\\n'\n"
    "                 'Settings \\u2192 Complaints\\n\\n'\n"
    "                 '\\u2022 Report wrong readings or billing disputes\\n'\n"
    "                 '\\u2022 Attach photos as evidence\\n'\n"
    "                 '\\u2022 Set priority and track status\\n\\n'\n"
    "                 'Email: support@meterscanner.com\\n'\n"
    "                 'Helpline: 1800-123-4567 (24/7 toll-free)')\n"
    "\n"
    "        elif any(w in msg for w in ['login','register','sign up','account','profile','password','google','logout']):\n"
    "            r = ('\\U0001f464 Account and Profile\\n\\n'\n"
    "                 'Login options:\\n'\n"
    "                 '\\u2022 \\U0001f511 Username and password\\n'\n"
    "                 '\\u2022 \\U0001f535 Google OAuth (one-click)\\n\\n'\n"
    "                 'Profile (Settings \\u2192 Profile): Update name, phone, address, change password\\n\\n'\n"
    "                 'Google Login: Click \\'Continue with Google\\' on the login page.\\n'\n"
    "                 'Account auto-created from your Google email! \\U0001f389\\n\\n'\n"
    "                 'New user? Click Register \\u2014 it\\'s free!')\n"
    "\n"
    "        elif any(w in msg for w in ['dashboard','overview','summary']):\n"
    "            r = ('\\U0001f4ca Dashboard Overview\\n\\n'\n"
    "                 '\\U0001f539 Average reading and scan count\\n'\n"
    "                 '\\U0001f539 Estimated bill\\n'\n"
    "                 '\\U0001f539 Usage change vs last month\\n'\n"
    "                 '\\U0001f539 Efficiency score (A+ to C)\\n'\n"
    "                 '\\U0001f539 Last 10 readings list\\n'\n"
    "                 '\\U0001f539 6-month trend chart\\n\\n'\n"
    "                 'Navigate: Scan, Readings, Alerts, Analytics from top navbar \\U0001f680')\n"
    "\n"
    "        elif any(w in msg for w in ['blurry','blur','not detected','dark','glare','problem','issue','cannot scan','trouble']):\n"
    "            r = ('\\U0001f527 Scanning Troubleshooting\\n\\n'\n"
    "                 '\\U0001f4f7 Blurry? Clean lens, hold steady, stay 15-25cm away\\n'\n"
    "                 '\\U0001f522 Not detected? All digits visible, avoid shadows\\n'\n"
    "                 '\\U0001f311 Too dark? Enable torch before scanning\\n'\n"
    "                 '\\u2600\\ufe0f Glare? Tilt phone slightly to reduce reflection\\n\\n'\n"
    "                 'Still stuck? Use Manual Entry on the scan screen!')\n"
    "\n"
    "        elif any(w in msg for w in ['thank','thanks','great','awesome','nice','helpful']):\n"
    "            r = 'You\\'re welcome! \\U0001f60a Happy to help anytime. \\u26a1'\n"
    "\n"
    "        elif any(w in msg for w in ['bye','goodbye','see you']):\n"
    "            r = 'Goodbye! \\U0001f44b Keep tracking your readings and saving energy! \\u26a1'\n"
    "\n"
    "        elif len(nums) >= 2:\n"
    "            u, rate = float(nums[0]), float(nums[1])\n"
    "            energy = u * rate; gst = energy * 0.18; total = energy + gst + 25\n"
    "            r = (f'\\U0001f4ca Detected {u} units at \\u20b9{rate}/unit\\n\\n'\n"
    "                 f'Energy \\u20b9{energy:.2f} + GST \\u20b9{gst:.2f} + Rent \\u20b925\\n'\n"
    "                 f'Total: \\u20b9{total:.2f}\\n\\nVisit Bills section for full breakdown!')\n"
    "\n"
    "        elif len(nums) == 1:\n"
    "            u = float(nums[0])\n"
    "            level = 'high \\U0001f534' if u > 500 else 'moderate \\U0001f7e1' if u > 200 else 'low \\U0001f7e2'\n"
    "            r = (f'Reading: {u} kWh \\u2014 Level: {level}\\n\\n'\n"
    "                 f\"Say 'calculate bill for {u} units' to get your estimate!\")\n"
    "\n"
    "        else:\n"
    "            r = ('I specialise in Meter Scanner Pro topics only. \\U0001f916\\n\\n'\n"
    "                 'Try asking:\\n'\n"
    "                 '\\u2022 \\'How do I scan my meter?\\'\\n'\n"
    "                 '\\u2022 \\'Calculate my bill for 300 units\\'\\n'\n"
    "                 '\\u2022 \\'How to set up alerts?\\'\\n'\n"
    "                 '\\u2022 \\'Show energy saving tips\\'\\n'\n"
    "                 '\\u2022 \\'How to export my data?\\'')\n"
    "\n"
    "        return jsonify({'response': r, 'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')})\n"
    "    except Exception as e:\n"
    "        app.logger.error(f'Chat error: {e}')\n"
    "        return jsonify({'response': 'Something went wrong. Please try again. \\U0001f605', 'error': str(e)}), 500\n"
    "\n"
)

new_content = content[:start_idx] + NEW_CHAT + content[end_idx:]

with open(r'd:\Riddhi\Meter_Scanner\app.py', 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Done. File size: {len(new_content)} chars")
